"use strict";
// Copyright 2025-2026, University of Colorado Boulder
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * FluentConstant is the type generated by generateFluentTypes for the entries in a SimFluent.ts file that require no inputs
 * for a pattern (i.e., constants that are interpolated using the fluent bundle but have no parameters).
 *
 * @author Sam Reid (PhET Interactive Simulations)
 * @author Jesse Greenberg (PhET Interactive Simulations)
 */
var DerivedProperty_js_1 = require("../../../axon/js/DerivedProperty.js");
var affirm_js_1 = require("../../../perennial-alias/js/browser-and-node/affirm.js");
var NO_STRING = '';
var FluentConstant = /** @class */ (function (_super) {
    __extends(FluentConstant, _super);
    /**
     * Creates a string Property that will update when the bundle changes.
     *
     * @param bundleProperty
     * @param key - The string key, where nesting is indicated by underscores (since that is compatible with Fluent syntax)
     *              such as a11y_summary_playAreaSummaryIntro
     * @param targetProperty - The target property that this FluentConstant will be associated with, solely for
     *                       - phet-io concerns because that is the PhET-iO instrumented part. see Text and RichText.
     *                       - This will be undefined in a built simulation when the corresponding string is unused.
     */
    function FluentConstant(bundleProperty, key, targetProperty) {
        var _this = _super.call(this, [bundleProperty], function (bundle) {
            var message = bundle.getMessage(key);
            var errors = [];
            // The message and value should be available during development. But the build removes unused strings.
            // FluentConstant is added to the Fluent.ts file during modulify so one will be created for all (even unused) keys.
            // Therefore, we must be graceful for the built simulation. We cannot assert or affirm because sometimes
            // assertions are kept in the build (like for debug).
            if (message && message.value) {
                var result = bundle.formatPattern(message.value, {}, errors);
                assert && assert(errors.length === 0, "Fluent errors found when formatting message: ".concat(errors));
                return result;
            }
            else {
                return NO_STRING;
            }
        }) || this;
        _this.targetProperty = targetProperty;
        return _this;
    }
    // For runtime "type checking" in PhetioObject. Note we cannot use instanceof FluentConstant there without causing a
    // cyclic dependency. This is used to help FluentConstant interoperate with the legacy phet-io instrumented string
    // requirements
    FluentConstant.prototype.hasTargetProperty = function () { return true; };
    /**
     * Returns the StringProperty for the given locale. See LocalizedStringProperty.getTranslatedStringProperty.
     * This only works for strings with no Fluent parameters or syntax. In order to support that, we would need a way to
     * look up the locale-specific string in the bundle. Since the use case for this is very rare, we are not going
     * to complicate the implementation with that right now. This is not implemented in FluentPattern because
     * those strings are expected to have parameters.
     */
    FluentConstant.prototype.getTranslatedStringProperty = function (locale) {
        (0, affirm_js_1.default)(this.targetProperty, 'If using getTranslatedStringProperty, the targetProperty must be defined. Why was it removed during the build?');
        return this.targetProperty.getTranslatedStringProperty(locale);
    };
    return FluentConstant;
}(DerivedProperty_js_1.DerivedProperty1));
exports.default = FluentConstant;
