"use strict";
// Copyright 2025-2026, University of Colorado Boulder
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        if (typeof b !== "function" && b !== null)
            throw new TypeError("Class extends value " + String(b) + " is not a constructor or null");
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.FluentPatternDerivedProperty = void 0;
/**
 * FluentPattern is the type generated by generateFluentTypes for the entries in a SimFluent.ts file that require inputs
 * for a pattern.
 *
 * @author Sam Reid (PhET Interactive Simulations)
 * @author Jesse Greenberg (PhET Interactive Simulations)
 */
var DerivedStringProperty_js_1 = require("../../../axon/js/DerivedStringProperty.js");
var TReadOnlyProperty_js_1 = require("../../../axon/js/TReadOnlyProperty.js");
var FluentUtils_js_1 = require("./FluentUtils.js");
var FluentPattern = /** @class */ (function () {
    /**
     *
     * @param bundleProperty
     * @param key - The string key, where nesting is indicated by underscores (since that is compatible with Fluent syntax)
     *              such as a11y_summary_playAreaSummaryIntro
     * @param targetProperty - The target property that this FluentConstant will be associated with, solely for phet-io studio autoselect, see Text and RichText.
     *                       - this will be undefined in a built simulation when the corresponding string is unused.
     * @param args - Shows the arguments that must be passed in to evaluate the pattern.
     */
    function FluentPattern(bundleProperty, key, targetProperty, args) {
        this.bundleProperty = bundleProperty;
        this.key = key;
        this.targetProperty = targetProperty;
        this.args = args;
    }
    FluentPattern.prototype.format = function (args) {
        var bundle = this.bundleProperty.value;
        var newArgs = FluentUtils_js_1.default.handleFluentArgs(args);
        var message = bundle.getMessage(this.key);
        // At runtime, users can edit the strings, using PhET-iO Studio or the PhET-iO API, so we must be graceful if something
        // goes wrong with the formatting.
        // In case of bad syntax, a target message may not be found.
        if (!message) {
            return "Fluent message not found for key: ".concat(this.key);
        }
        var errors = [];
        var result = bundle.formatPattern(message.value, newArgs, errors);
        // At runtime, users can edit the strings, using PhET-iO Studio or the PhET-iO API, so we must be graceful if something
        // goes wrong with the formatting.
        if (errors.length > 0) {
            return "Fluent errors found when formatting message: ".concat(errors.map(function (error) { return error.message; }).join(', '));
        }
        return result;
    };
    /**
     * Creates a StringProperty that will update when the bundle changes or any of the args change.
     * Clients are responsible for disposing of the StringProperty, if it is short-lived.
     *
     * @param args - The arguments to be passed to the Fluent pattern, like MembraneTransportFluent.myPattern.format({ numberOfSolutes: model.numberOfSolutesProperty});
     */
    FluentPattern.prototype.createProperty = function (args) {
        var _this = this;
        var dependencies = _.uniq(__spreadArray([this.bundleProperty], Object.values(args).filter(TReadOnlyProperty_js_1.isTReadOnlyProperty), true));
        return new FluentPatternDerivedProperty(dependencies, function () { return _this.format(args); }, this.targetProperty);
    };
    /**
     * Returns all of the Properties that should be listened to in order to determine if results from format() need to be
     * recomputed.
     */
    FluentPattern.prototype.getDependentProperties = function () {
        return [this.bundleProperty];
    };
    return FluentPattern;
}());
exports.default = FluentPattern;
/**
 * Adds support for targetProperty for phet-io studio autoselect.
 */
var FluentPatternDerivedProperty = /** @class */ (function (_super) {
    __extends(FluentPatternDerivedProperty, _super);
    /**
     * @param dependencies
     * @param args
     * @param targetProperty - the target property that this FluentPatternDerivedProperty will be associated with, solely for phet-io studio autoselect, see Text and RichText.
     *                       - this will be undefined in a built simulation when the corresponding string is unused.
     */
    function FluentPatternDerivedProperty(dependencies, args, targetProperty) {
        var _this = _super.call(this, dependencies, args) || this;
        _this.targetProperty = targetProperty;
        return _this;
    }
    return FluentPatternDerivedProperty;
}(DerivedStringProperty_js_1.default));
exports.FluentPatternDerivedProperty = FluentPatternDerivedProperty;
